<script setup lang="ts">
import { computed, nextTick, ref } from 'vue'
import { onReady } from '@dcloudio/uni-app'
import { patternPixelSize, placementPixelPoint, pixelPointToPlacement } from '../../features/editor/domain/geometry'
import type { PatternPlacement, PixelSize } from '../../features/editor/domain/types'
import { useEditorStore } from '../../features/editor/stores/editor'
interface ZoneRect extends PixelSize { left: number; top: number }
interface TouchLikeEvent { touches: { length: number; [index: number]: { clientX: number; clientY: number } } }
const editor = useEditorStore(); const zoneRect = ref<ZoneRect | null>(null); const dragging = ref<{ id: string; offsetX: number; offsetY: number } | null>(null)
const price = (cents: number) => `¥${(cents / 100).toFixed(2)}`
const selectedPattern = computed(() => editor.selectedPlacement ? editor.getPattern(editor.selectedPlacement.patternId) : null)
function measure(): void { nextTick(() => uni.createSelectorQuery().select('.embroidery-zone').boundingClientRect((rect) => { if (rect) { const box = rect as ZoneRect; zoneRect.value = { left: box.left, top: box.top, width: box.width, height: box.height } } }).exec()) }
function placementStyle(placement: PatternPlacement): Record<string, string> { if (!zoneRect.value) return { visibility: 'hidden' }; const pattern = editor.getPattern(placement.patternId); const point = placementPixelPoint(placement, pattern, editor.bag.embroideryArea, zoneRect.value); const size = patternPixelSize(pattern, editor.bag.embroideryArea, zoneRect.value); return { width: `${size.width}px`, height: `${size.height}px`, transform: `translate3d(${point.x}px,${point.y}px,0)` } }
function choose(id: string): void { editor.selectedPlacement ? editor.replaceSelected(id) : editor.addPattern(id) }
function start(placement: PatternPlacement, event: TouchLikeEvent): void { if (!zoneRect.value || !event.touches[0]) return; editor.selectPlacement(placement.id); const pattern = editor.getPattern(placement.patternId); const point = placementPixelPoint(placement, pattern, editor.bag.embroideryArea, zoneRect.value); dragging.value = { id: placement.id, offsetX: event.touches[0].clientX - zoneRect.value.left - point.x, offsetY: event.touches[0].clientY - zoneRect.value.top - point.y } }
function move(event: TouchLikeEvent): void { if (!dragging.value || !zoneRect.value || !event.touches[0]) return; const placement = editor.placements.find((item) => item.id === dragging.value?.id); if (!placement) return; editor.updatePlacement(pixelPointToPlacement({ x: event.touches[0].clientX - zoneRect.value.left - dragging.value.offsetX, y: event.touches[0].clientY - zoneRect.value.top - dragging.value.offsetY }, placement, editor.getPattern(placement.patternId), editor.bag.embroideryArea, zoneRect.value)) }
onReady(measure)
</script>
<template>
  <view class="page"><view class="header"><text class="eyebrow">固定尺寸 DIY 技术验证</text><text class="title">{{ editor.bag.name }}</text><text class="meta">真实尺寸 {{ editor.bag.width }} × {{ editor.bag.height }} mm</text></view>
    <view class="stage"><image class="bag" :src="editor.bag.imageUrl" mode="aspectFit"/><view class="embroidery-zone" @tap="editor.selectPlacement(null)" @touchmove.stop.prevent="move" @touchend="dragging = null"><text class="zone-label">刺绣区域 {{ editor.bag.embroideryArea.width }} × {{ editor.bag.embroideryArea.height }} mm</text><view v-for="placement in editor.placements" :key="placement.id" class="placed" :class="{ selected: placement.id === editor.selectedPlacementId }" :style="placementStyle(placement)" @tap.stop="editor.selectPlacement(placement.id)" @touchstart.stop="start(placement, $event)"><image :src="editor.getPattern(placement.patternId).imageUrl" mode="aspectFit"/></view></view></view>
    <view class="price-card"><view><text>包包价格</text><text>{{ price(editor.bag.basePriceCents) }}</text></view><view><text>图案价格</text><text>{{ price(editor.patternPriceCents) }}</text></view><view class="total"><text>总价</text><text>{{ price(editor.totalPriceCents) }}</text></view></view>
    <view class="panel"><view class="tabs"><button v-for="category in editor.categories" :key="category.id" :class="{ active: category.id === editor.activeCategoryId }" @tap="editor.activeCategoryId = category.id">{{ category.name }}</button></view><view class="catalog"><button v-for="pattern in editor.activePatterns" :key="pattern.id" @tap="choose(pattern.id)"><image :src="pattern.imageUrl" mode="aspectFit"/><text>{{ pattern.name }}</text><text class="small">{{ pattern.width }}×{{ pattern.height }} mm</text><text class="small">{{ price(pattern.priceCents) }}</text></button></view></view>
    <view v-if="selectedPattern" class="selected-bar"><text>已选 {{ selectedPattern.name }}（固定 {{ selectedPattern.width }} × {{ selectedPattern.height }} mm，不可缩放或旋转）</text><button @tap="editor.deleteSelected">删除</button></view>
    <view class="draft"><text>草稿已自动保存；位置使用中心比例坐标。</text><text v-for="item in editor.placements" :key="item.id">{{ editor.getPattern(item.patternId).name }}：({{ item.centerXRatio.toFixed(4) }}, {{ item.centerYRatio.toFixed(4) }})</text><button @tap="editor.clearDraft">清空草稿</button></view>
  </view>
</template>
<style scoped>
.page{min-height:100vh;padding:28rpx;background:#f8f2eb;color:#392b26}.header{display:flex;flex-direction:column;gap:8rpx}.eyebrow{color:#a0654c;font-size:23rpx}.title{font-size:46rpx;font-weight:700}.meta,.small{color:#88766d;font-size:22rpx}.stage{position:relative;margin:28rpx auto;width:680rpx;height:540rpx}.bag{width:100%;height:100%}.embroidery-zone{position:absolute;left:120rpx;top:172rpx;width:460rpx;height:252rpx;overflow:hidden;border:3rpx dashed #714733;background:rgba(255,255,255,.16);touch-action:none}.zone-label{position:absolute;right:8rpx;bottom:6rpx;color:#704834;font-size:18rpx}.placed{position:absolute;left:0;top:0;touch-action:none}.placed image{width:100%;height:100%}.selected{outline:3rpx solid white;outline-offset:2rpx}.price-card,.panel,.draft{margin-top:20rpx;padding:24rpx;border-radius:20rpx;background:#fff;box-shadow:0 6rpx 20rpx #754f3220}.price-card{display:flex;justify-content:space-between}.price-card view{display:flex;flex-direction:column;gap:8rpx;font-size:25rpx}.total{color:#b74b34;font-weight:700}.tabs{display:flex;gap:12rpx;margin-bottom:16rpx}.tabs button{font-size:24rpx;background:#f4e8dc}.tabs .active{background:#a86849;color:#fff}.catalog{display:grid;grid-template-columns:repeat(3,1fr);gap:12rpx}.catalog button{padding:12rpx 6rpx;background:#fff9f4;border:1rpx solid #ead9cb;font-size:23rpx}.catalog image{width:66rpx;height:66rpx;display:block;margin:auto}.catalog text{display:block}.selected-bar{display:flex;justify-content:space-between;align-items:center;margin-top:20rpx;padding:18rpx;background:#fff0e4;border-radius:16rpx;font-size:23rpx}.selected-bar button,.draft button{margin:0;font-size:22rpx;color:#b24638;background:#fff}.draft{display:flex;flex-direction:column;gap:8rpx;font-size:22rpx;color:#75665f}
</style>
