<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { bagApi, type Bag } from '../services/api'

const bags = ref<Bag[]>([]); const loading = ref(false); const dialogVisible = ref(false); const formRef = ref<FormInstance>(); const editingId = ref<string | null>(null)
const form = reactive({ name: '', image_asset_id: '', width_mm: 280, height_mm: 220, base_price_cents: 15900, status: 'draft' })
const rules: FormRules = { name: [{ required: true, message: '请输入包包名称', trigger: 'blur' }], image_asset_id: [{ required: true, message: '请先上传包包图片并填写资源 ID', trigger: 'blur' }], width_mm: [{ required: true, type: 'number', min: 1, message: '宽度必须大于 0', trigger: 'blur' }], height_mm: [{ required: true, type: 'number', min: 1, message: '高度必须大于 0', trigger: 'blur' }] }
async function load(): Promise<void> { loading.value = true; try { bags.value = await bagApi.list() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '加载失败') } finally { loading.value = false } }
function openCreate(): void { editingId.value = null; Object.assign(form, { name: '', image_asset_id: '', width_mm: 280, height_mm: 220, base_price_cents: 15900, status: 'draft' }); dialogVisible.value = true }
function openEdit(row: Bag): void { editingId.value = row.id; Object.assign(form, row); dialogVisible.value = true }
async function submit(): Promise<void> { if (!formRef.value || !(await formRef.value.validate().catch(() => false))) return; try { const payload = { ...form }; if (editingId.value) await bagApi.update(editingId.value, payload); else await bagApi.create(payload); ElMessage.success('保存成功'); dialogVisible.value = false; await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '保存失败') } }
async function changeStatus(row: Bag, status: string): Promise<void> { const action = status === 'archived' ? '归档' : status === 'published' ? '上架' : '下架'; try { await ElMessageBox.confirm(`确认${action}“${row.name}”吗？`, '二次确认', { type: 'warning' }); await bagApi.setStatus(row.id, status); ElMessage.success(`${action}成功`); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '操作失败') } }
onMounted(load)
</script>
<template><section><el-page-header content="包包管理" /><div class="toolbar"><el-button type="primary" @click="openCreate">新增包包</el-button><el-button @click="load">刷新</el-button></div><el-table :data="bags" v-loading="loading"><el-table-column prop="name" label="名称"/><el-table-column label="真实尺寸"><template #default="{ row }">{{ row.width_mm }} × {{ row.height_mm }} mm</template></el-table-column><el-table-column label="基础价格"><template #default="{ row }">¥{{ (row.base_price_cents / 100).toFixed(2) }}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="280"><template #default="{ row }"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link type="success" @click="changeStatus(row, 'published')">上架</el-button><el-button link type="warning" @click="changeStatus(row, 'unpublished')">下架</el-button><el-button link type="danger" @click="changeStatus(row, 'archived')">归档</el-button></template></el-table-column></el-table><el-empty v-if="!loading && bags.length === 0" description="暂无包包，请先上传图片并新增包包" /></section><el-dialog v-model="dialogVisible" :title="editingId ? '编辑包包' : '新增包包'" width="580px"><el-form ref="formRef" :model="form" :rules="rules" label-width="110px"><el-form-item label="名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="图片资源 ID" prop="image_asset_id"><el-input v-model="form.image_asset_id" placeholder="图片上传接口返回的 ID" /></el-form-item><el-form-item label="真实宽度" prop="width_mm"><el-input-number v-model="form.width_mm" :min="1" /> mm</el-form-item><el-form-item label="真实高度" prop="height_mm"><el-input-number v-model="form.height_mm" :min="1" /> mm</el-form-item><el-form-item label="基础价格"><el-input-number v-model="form.base_price_cents" :min="0" /> 分</el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></template></el-dialog></template>
<style scoped>.toolbar{display:flex;gap:12px;margin:20px 0}</style>
