<script setup lang="ts">
import { computed, ref } from 'vue'
import { useEditorStore } from '../../features/editor/stores/editor'
import { catalogApi } from '../../services/catalog-api'
const editor = useEditorStore(); const loading = ref(false); const price = (cents: number) => `¥${(cents / 100).toFixed(2)}`
const serverTotal = computed(() => editor.savedDesign?.totalPriceCents ?? editor.totalPriceCents)
function back(): void { uni.navigateBack({ fail: () => uni.redirectTo({ url: '/pages/editor/index' }) }) }
async function addCart(): Promise<void> { if (!editor.savedDesign) return; loading.value = true; try { await catalogApi.addCartItem(editor.savedDesign.id, editor.clientKey()); uni.showToast({ title: '已加入购物车', icon: 'success' }); uni.navigateTo({ url: '/pages/cart/index' }) } catch (e) { uni.showToast({ title: e instanceof Error ? e.message : '加入购物车失败', icon: 'none' }) } finally { loading.value = false } }
async function createOrder(): Promise<void> { if (!editor.savedDesign) return; loading.value = true; try { await catalogApi.createOrder(editor.savedDesign.id, editor.clientKey()); uni.showToast({ title: '模拟订单已创建', icon: 'success' }); uni.redirectTo({ url: '/pages/orders/index' }) } catch (e) { uni.showToast({ title: e instanceof Error ? e.message : '创建订单失败', icon: 'none' }) } finally { loading.value = false } }
</script>
<template><view class="page"><text class="title">设计确认</text><view v-if="!editor.catalogLoaded || !editor.savedDesign" class="empty"><text>没有可确认的已保存设计。</text><button @tap="back">返回编辑器</button></view><template v-else><view class="ok">设计已保存，后端已重新计算价格。</view><view class="card"><image :src="editor.bag.imageUrl" mode="aspectFit"/><text>{{ editor.bag.name }} · 基础价格 {{ price(editor.bag.basePriceCents) }}</text></view><view class="card"><text class="sub">图案清单</text><view v-for="item in editor.placements" :key="item.id" class="line"><text>{{ editor.getPattern(item.patternId).name }}（固定 {{ editor.getPattern(item.patternId).width }} × {{ editor.getPattern(item.patternId).height }} mm，{{ item.rotationDegrees }}°）</text><text>{{ price(editor.getPattern(item.patternId).priceCents) }}</text></view><view class="line total"><text>后端确认总价</text><text>{{ price(serverTotal) }}</text></view></view><view class="actions"><button @tap="back">继续编辑</button><button :loading="loading" @tap="addCart">加入购物车</button><button class="primary" :loading="loading" @tap="createOrder">立即创建订单</button></view></template></view></template>
<style scoped>.page{min-height:100vh;padding:28rpx;background:#f6f4f1}.title{display:block;font-size:42rpx;font-weight:700}.empty{display:flex;min-height:50vh;align-items:center;justify-content:center;flex-direction:column;gap:20rpx}.ok{margin-top:18rpx;padding:18rpx;color:#4b852f;background:#f0f9eb;border-radius:14rpx}.card{margin-top:18rpx;padding:20rpx;background:#fff;border-radius:18rpx;display:flex;gap:16rpx;flex-direction:column}.card image{width:220rpx;height:170rpx}.line{display:flex;justify-content:space-between;gap:14rpx;font-size:23rpx}.sub{font-weight:700}.total{padding-top:16rpx;color:#d75a49;font-size:28rpx;font-weight:700}.actions{display:flex;gap:12rpx;margin-top:22rpx}.actions button{flex:1;font-size:21rpx}.primary{color:#fff;background:#fa7770}</style>
