"""create core diy models

Revision ID: 3e3f1bea2a32
Revises: 
Create Date: 2026-07-16 15:29:41.437154
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e3f1bea2a32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('file_assets',
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('pattern_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bags',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['file_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('production_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pattern_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_code')
    )
    op.create_table('designs',
    sa.Column('bag_id', sa.Uuid(), nullable=False),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('preview_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.ForeignKeyConstraint(['preview_asset_id'], ['file_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embroidery_areas',
    sa.Column('bag_id', sa.Uuid(), nullable=False),
    sa.Column('relative_x', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('relative_y', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('relative_width', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('relative_height', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bag_id')
    )
    op.create_table('pattern_versions',
    sa.Column('pattern_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['file_assets.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_items',
    sa.Column('design_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_version_id', sa.Uuid(), nullable=False),
    sa.Column('center_x_ratio', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('center_y_ratio', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['pattern_version_id'], ['pattern_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_items')
    op.drop_table('pattern_versions')
    op.drop_table('embroidery_areas')
    op.drop_table('designs')
    op.drop_table('patterns')
    op.drop_table('bags')
    op.drop_table('pattern_categories')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
